# Site settings
title: Lyle Mullican
email: "ldmullican (at) gmail (dot) com"
description: > 
  Rubyist, User Advocate, Visual Artist, Writer
baseurl: ""
url: "http://lylemullican.com"
twitter_username: mullican
github_username:  mullican
linkedin_username:  mullican
facebook_username:  mullican

# Build settings
markdown: kramdown
